# week04/k8s/customer-db.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-db-pvc
spec:
  accessModes:
    - ReadWriteOnce # This volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db-deployment
  labels:
    app: customer-db
spec:
  replicas: 1 # Defaulting to 1 replica
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: CUSTOMERS_DB_NAME # Point to the customer database name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: customer-db-storage
          mountPath: /var/lib/postgresql/data # Mount point for PostgreSQL data
      volumes:
      - name: customer-db-storage
        persistentVolumeClaim:
          claimName: customer-db-pvc # Link to the PVC defined above
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db-service # Internal DNS name for the Customer DB
  labels:
    app: customer-db
spec:
  selector:
    app: customer-db # Selects pods with the label app: customer-db
  ports:
    - protocol: TCP
      port: 5432 # The port the service listens on (default PostgreSQL)
      targetPort: 5432 # The port on the Pod (containerPort)
  type: ClusterIP # Only accessible from within the cluster