# week04/k8s/customer-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  replicas: 1 # Defaulting to 1 replica
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service-container
        image: <your_image_name>
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        env:
        # Database connection details
        - name: POSTGRES_HOST
          value: customer-db-service
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: CUSTOMERS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 8002 # The port the service listens on inside the cluster
      targetPort: 8000 # The port on the Pod (containerPort)
      nodePort: 30002 # A high port (30000-32767) on your host machine to access the service (distinct)
  type: NodePort # Exposes the service on a port on each Node's IP