# week04/k8s/order-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1 # Defaulting to 1 replica
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-container
        image: <your_image_name>
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        env:
        # Database connection details
        - name: POSTGRES_HOST
          value: order-db-service
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: ORDERS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
        
        # RabbitMQ connection for publishing order events
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: RABBITMQ_HOST
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: RABBITMQ_PASS
        - name: CUSTOMER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: CUSTOMER_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
      nodePort: 30001
  type: NodePort
