# week04/k8s/product-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1 # Defaulting to 1 replica
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service-container
        image: <your_image_name>
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: product-db-service
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: PRODUCTS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
        - name: AZURE_STORAGE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: AZURE_STORAGE_ACCOUNT_NAME
        - name: AZURE_STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: secrets
              key: AZURE_STORAGE_ACCOUNT_KEY
        - name: AZURE_STORAGE_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: AZURE_STORAGE_CONTAINER_NAME
        - name: AZURE_SAS_TOKEN_EXPIRY_HOURS
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: AZURE_SAS_TOKEN_EXPIRY_HOURS
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: RABBITMQ_HOST
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: RABBITMQ_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
